# Example template - please customize for setup
version: "3.9"

services:
  palworld:
    image: ghcr.io/ripps818/palworld-wine:latest
    container_name: palworld-wine
    ports:
      - 8211:8211/udp # Required UDP game Port
      - 25575:25575 # Optional RDP port
      - 27015:27015 # Optional Query port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - MULTITHREADING=true
    volumes:
      - ./palworld/app:/app # Where Steamcmd and Palworld is going to live
      - ./palworld/backup:/backup # Palworld Backup Locations
    restart: unless-stopped
    